#!/usr/bin/env python3
"""
Generate a packing checklist for a trip.

Usage:
  python generate_checklist.py --types road air --trip "Portland Weekend" --days 3
  python generate_checklist.py --types international --trip "Japan 2026" --days 14 --output trips/japan-2026.md
  python generate_checklist.py --list-types
"""

import argparse
import sys
from datetime import date
from pathlib import Path

import yaml

VALID_TYPES = ["road", "air", "international"]
ITEMS_FILE = Path(__file__).parent / "items.yaml"


def load_items(path: Path) -> list[dict]:
    with open(path) as f:
        data = yaml.safe_load(f)
    return data["categories"]


def filter_items(categories: list[dict], trip_types: list[str]) -> list[dict]:
    result = []
    for category in categories:
        items = [
            item for item in category["items"]
            if any(t in item.get("tags", []) for t in trip_types)
        ]
        if items:
            result.append({"name": category["name"], "items": items})
    return result


def render_markdown(trip_name: str, trip_types: list[str], days: int, categories: list[dict]) -> str:
    lines = []
    lines.append(f"# Packing List: {trip_name}")
    lines.append(f"**Trip type:** {', '.join(trip_types)}  ")
    lines.append(f"**Duration:** {days} day{'s' if days != 1 else ''}  ")
    lines.append(f"**Generated:** {date.today().isoformat()}")
    lines.append("")

    for category in categories:
        lines.append(f"## {category['name']}")
        lines.append("")
        for item in category["items"]:
            required = item.get("required", False)
            condition = item.get("condition", "")
            marker = "- [ ]"
            name = item["name"]
            note = f"  _{condition}_" if condition else ""
            req_marker = "" if required else " *(optional)*"
            lines.append(f"{marker} {name}{req_marker}{note}")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by trip-planning/packing/generate_checklist.py*")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate a packing checklist")
    parser.add_argument("--types", nargs="+", choices=VALID_TYPES, metavar="TYPE",
                        help=f"Trip type(s): {', '.join(VALID_TYPES)}")
    parser.add_argument("--trip", default="My Trip", help="Trip name (used in header)")
    parser.add_argument("--days", type=int, default=7, help="Number of days")
    parser.add_argument("--output", "-o", help="Output file path (default: print to stdout)")
    parser.add_argument("--list-types", action="store_true", help="Show available trip types")
    parser.add_argument("--all", action="store_true", help="Include all items regardless of type")
    args = parser.parse_args()

    if args.list_types:
        print("Available trip types:")
        for t in VALID_TYPES:
            print(f"  {t}")
        return

    if not args.types and not args.all:
        parser.error("Specify --types or --all")

    trip_types = VALID_TYPES if args.all else args.types
    categories = load_items(ITEMS_FILE)
    filtered = filter_items(categories, trip_types)
    markdown = render_markdown(args.trip, trip_types, args.days, filtered)

    if args.output:
        out = Path(args.output)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(markdown)
        print(f"Checklist written to {out}")
    else:
        print(markdown)


if __name__ == "__main__":
    main()
